version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package_1.zip .
      - zip -r9 ../deployment_package_2.zip .
      - cd ..
      - cd Lambdas
      - mv search_photos.py ../lambda_function.py
      - cd ..
      - zip -r deployment_package_1.zip lambda_function.py
      - mv lambda_function.py Lambdas/search_photos.py
      - cd Lambdas
      - mv LF1_2.py ../lambda_function.py
      - cd ..
      - zip -r deployment_package_2.zip lambda_function.py
      - mv lambda_function.py Lambdas/LF1_2.py

  post_build:
    commands:
      - echo "Updating lambda Functions..."
      - aws lambda update-function-code --function-name search_photos --zip-file fileb://deployment_package_1.zip
      - aws lambda update-function-code --function-name LF1_2 --zip-file fileb://deployment_package_2.zip
      - echo "DONE!!"
