AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LF1Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: LF1_2.lambda_handler
      Runtime: python3.9
      CodeUri: ./Lambdas/
  LF2Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: search_photos.lambda_handler
      Runtime: python3.9
      CodeUri: ./Lambdas/